== IMA Token Access Control
:doctype: article
:!showtitle:
:icons: font
:toc: macro

ifdef::env-github[]

:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:

endif::[]

=== Introduction

The SKALE Chain owner has special permissions to setup specific IMA parameters, such as IMA access control. These permissions include:

* Enable/disable whitelist (default: enabled)
* AddERC20TokenByOwner
* AddERC721TokenByOwner

toc::[]

=== Enable/Disable the Whitelist

The Token whitelist allows the Schain owner to control or allow token exchange through IMA and the SKALE chain. For example, a decentralized exchange may prefer to disable the whitelist. A dApp using only one token may enable the whitelist to allow only a single token exchange. 

To disable the whitelist, the owner executes `disableWhitelist` in LockAndDataForMainnetERC20 or LockAndDataForMainnetERC721 contracts, and pass in the schainName as the only argument. For example:

```python
lock_and_data_for_mainnet_erc20 = self._get_contract_on_mainnet('lock_and_data_for_mainnet_erc20')
disable = lock_and_data_for_mainnet_erc20.encodeABI(fn_name="disableWhitelist", args=[schainName])

signed_txn = self.web3_mainnet.eth.account.signTransaction(dict(
        nonce=self.web3_mainnet.eth.getTransactionCount(sender_address),
        gasPrice=self.web3_mainnet.eth.gasPrice,
        gas=200000,
        to=lock_and_data_for_mainnet_erc20.address,
        value=0,
        data = disable
    ),
    from_key)

self.web3_mainnet.eth.sendRawTransaction(signed_txn.rawTransaction)
```

To re-enable the whitelist, the owner executes `enableWhitelist` as demonstrated above.

=== Adding ERC20 tokens

`addERC20TokenByOwner` takes the SKALE Chain owner private key, schainName, and ERC20 Address

For example:

```python
lock_and_data_for_mainnet_erc20 = self._get_contract_on_mainnet('lock_and_data_for_mainnet_erc20')
addERC20 = lock_and_data_for_mainnet_erc20.encodeABI(fn_name="addERC20TokenByOwner", args=[schainName, erc20Address])

signed_txn = self.web3_mainnet.eth.account.signTransaction(dict(
        nonce=self.web3_mainnet.eth.getTransactionCount(sender_address),
        gasPrice=self.web3_mainnet.eth.gasPrice,
        gas=200000,
        to=lock_and_data_for_mainnet_erc20.address,
        value=0,
        data = addERC20
    ),
    from_key)

self.web3_mainnet.eth.sendRawTransaction(signed_txn.rawTransaction)
```

=== Adding ERC721 tokens

```python
lock_and_data_for_mainnet_erc721 = self._get_contract_on_mainnet('lock_and_data_for_mainnet_erc721')
addERC721 = lock_and_data_for_mainnet_erc721.encodeABI(fn_name="addERC721TokenByOwner", args=[schainName, erc721Address])

signed_txn = self.web3_mainnet.eth.account.signTransaction(dict(
        nonce=self.web3_mainnet.eth.getTransactionCount(sender_address),
        gasPrice=self.web3_mainnet.eth.gasPrice,
        gas=200000,
        to=lock_and_data_for_mainnet_erc721.address,
        value=0,
        data = addERC721
    ),
    from_key)

self.web3_mainnet.eth.sendRawTransaction(signed_txn.rawTransaction)
```