= Message Proxy

The MessageProxy contract sends messages to any contract. The IMA system uses MessageProxy to send Eth, ERC20, ERC721 transfer messages to DepositBox and TokenManager contracts, and can be expanded to support other arbitrary messages and contracts.

== Architecture

* MessageProxy contracts are deployed on Mainnet and each SKALE Chain.
* OutgoingMessages are processed by IMA Agent, a containerized nodejs script operating on each SKALE Node. When the Agent receives an OutgoingMessage, it sends the message to another MessageProxy contract on the destination chain to which it's sent.
* PostOutgoingMessage is a function called by DepositBox and TokenManager, when a transfer is initiated to another chain (Mainnet or SKALE Chain)

== Implementation

To send messages via MessageProxy, your contract(s) on the SKALE Chain or Mainnet need to call postOutgoingMessage() on the MessageProxy to send messages through the Agent. You need to pass in the arguments for destinationChainID, destination contract address, and the data to be sent. If you send messages from Schain to Mainnet, you must call MessageProxyOnSchain's postOutGoingMessage() and include destinationChainID = "Mainnet" and the receiving contract address on Mainnet.

To receive messages via MessageProxy, your contract(s) need to implement postMessage(). The Agent only calls this function.

When the source contract calls PostOutgoingMessage(), the `data` will be delivered to the destination contract via the Agent. The Agent will then call on the postMessage() function on the destination contract to deliver the message.

For example, 

To send messages from SKALE Chain to Mainnet:
* Your SKALE chain contract(s) must call `PostOutgoingMessage("Mainnet", [RECEIVING_CONTRACT_ADDRESS_ON_MAINNET], 0, [FINAL RECEIVER/CONTRACT ADDRESS], [DATA])`
* The receiving contract address on mainnet must implement `postMessage()` function.

To send messages from Mainnet to SKALE Chain:
* Your Mainnet contract(s) must call `PostOutgoingMessage([SKALE_CHAIN_ID], [RECEIVING_CONTRACT_ADDRESS_ON_SCHAIN], 0, [FINAL RECEIVER/CONTRACT ADDRESS_ON_SCHAIN], [DATA])`
* The receiving contract address on SKALE Chain must implement `postMessage()` function.