= Node SSL Setup
:icons: font
:toc: macro

ifdef::env-github[]

:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:

endif::[]

toc::[]

=== General info
Node SSL certificates are used for secure communication with sChain endpoints. By default, each node of the sChain listens on HTTP and WS ports, but if SSL certs are uploaded to the node HTTPS and WSS ports are also turned on. 

Node SSL certificates aren't required to start a node, register it, or create sChains. But because dApp developers often use toolings that require HTTPS/WSS endpoints, SSL certificates are required. 

=== Validators onboarding
Here's an example of a step-by-step process of setting up validator node SSL. 

==== Prerequisites 
To upload SSL certificates to the node, you’ll have to do a few steps on your side which may vary depending on your domain name provider, certificate authority, etc. We’ll provide you a reference example of how this could be achieved using free Let's Encrypt certificates at the end of this post. 

The steps include getting domain names for each node, issuing SSL certificates for them, and uploading them to the node.

[NOTE]
This procedure will vary depending on your domain management service (Google Domains, GoDaddy, etc).

Step 1. Domain name and redirects::
    The first thing you will need is the domain name. You’ll need one per node so it makes sense to set up a subdomain for each one and setup redirects. Let’s say you own `awesome-validator.com` and run 2 nodes with the following IP addresses, names, and redirects:

[%header,cols=3*]
|===
| Node name
| Node IP
| Redirect

|node-0
|123.1.23.5
|node-0.awesome-validator.com

|node-1
|5.46.34.25
|node-1.awesome-validator.com
|===

Step 2. Verify redirects::
You can verify that redirects work by sending a request to the watchdog API on 3009 port using your domain name.

Step 3. Issue SSL certificates:: Once you have all redirects for your nodes you can move to the SSL certificates. You will need SSL certs issued by one of the trusted CA:

(todo: list of trusted CAs)

Once you've decided on the certificate issuer you have several options - issue a separate certificate for each subdomain (node-0.awesome-validator.com, node-1.awesome-validator.com) or issue a single Wildcard SSL for all nodes (*.awesome-validator.com).

As a result, you should have 2 main files:

Certificate file (usually called something like fullchain.pem or cert.pem)

Private key file (usually called something like privkey.pem, pk.pem)

Save them and copy them to the respecting nodes.

Step 4. Upload certificates to the SKALE Node:: We’re almost here, this is the last step. Once you copied the certificate and private key file, all you have to do is to run the following command:

```shell
skale ssl upload -c $PATH_TO_CERT_FILE -k $PATH_TO_KEY_FILE
```

[NOTE]
Add -f flag to the command to override existing certificates on the node

Once certificates are uploaded, you can check them by running:

```shell
skale ssl status
```

Full reference could be found here: https://github.com/skalenetwork/node-cli[skalenetwork/node-cli]. 

=== Trusted authorities
When choosing CA for getting your SSL certificate, consider a source that will be trusted by most major browsers, operating systems, and other devices.

Here’s a list of links that can help you with your decision:

* List of major CA providers: https://en.wikipedia.org/wiki/Certificate_authority#Providers
* CAs trusted by Mozilla: https://wiki.mozilla.org/CA/Included_Certificates
* CAs trusted by Apple: https://support.apple.com/en-us/HT204132, https://support.apple.com/en-us/HT209144

Also, here’s a list of the most popular and well-known SSL providers:

* DigiCert (https://www.digicert.com/)
* GeoTrust (https://www.geotrust.com/)
* RapidSSL (https://www.rapidssl.com/)

Besides that, usually, you could purchase an SSL certificate from your domain provider. That could be the most convenient way for you to manage everything from a single place:

* GoDaddy (https://godaddy.com/web-security/ssl-certificate)
* NameCheap (http://namecheap.com/)
* Name.com (https://www.name.com/ssl)

Most of them usually providing you with a few options like RapidSSL and DigiCert.

[WARNING]
Certificates provided by Letsencrypt are widely used now and trusted by most operating systems and devises so it’s OK to use them for your node, but don't forget about renewals, since Letsencrypt certs expire in 3 months. You can read more about Letsencrypt security and trust here: https://letsencrypt.org/certificates/ and https://letsencrypt.org/2018/08/06/trusted-by-all-major-root-programs.html
 
[NOTE]
Generally, Letsencrypt SSL certs are considered as a safe thing, but there are some opponents to the idea of a 'free SSL certs for everybody': https://medium.com/swlh/why-lets-encrypt-is-a-really-really-really-bad-idea-d69308887801

=== Reference tutorial (Wildcard SSL using Letsencrypt)
Step 1. Install Certbot::
https://certbot.eff.org/lets-encrypt/ubuntufocal-nginx

Step 2. Run::

```shell
certbot certonly --standalone -d my.domain.com
```

Step 3. Copy .pem files to secure place:: 
```shell
cp *.pem ~/[SECURE_DIR]
```

=== Setting domain name on SKALE Manager contracts

Step 1::
```shell
skale node set-domain
```

Step 2::
Enter the domain name to set for this node.

```shell
> Enter domain name: node-0.awesome-validator.com
```

Adding domain name for an existing node
todo

Registering a new node with a domain name 
todo

Retrieving sChain endpoints
🏗 This section will contain explanations for dApp users/owners about how to get all 64 sChain endpoints (including HTTP, HTTPS, WS and WSS) with the domain name.